# Path to adapt by user
output_dir: 
    junction_annotation: ../../data/results/als/junction_annotation/
    splicing_preds: ../../data/results/als/splicing_predictions/
    outliers: ../../data/results/als/outlier_ground_truth/
    vcf_annotation: ../../data/results/als/vcf_annotation/
    benchmark: ../../data/results/als/benchmark/
    proteomics: ../../data/results/als/proteomics/
    reports: ../../data/als/reports/

genome: 'hg38'
fasta: /s/genomes/human/hg38/gencode.v38/GRCh38.primary_assembly.genome.fa
gtf: /s/genomes/human/hg38/gencode.v38/gencode.v38.annotation.gtf

gene_count: ../../data/resources/als/AnswerALS-290-T-v1-release5_rna-counts-matrix.csv
        
vcf: ../../data/resources/als/vcf_normalized/{vcf_id}.vcf.gz

DROP:
    outlier_ground_truth_all: ../../data/resources/als/DROP/processed_results/aberrant_splicing/results/v38/fraser/
    tissue_map: ../../data/resources/als/tissue_map_DROP.csv
    sample_annotation_pure: ../../data/resources/als/sample_annotation_drop_pure.tsv
    sample_annotation: ../../data/resources/als/sample_annotation_drop.tsv
    version: 'v38'
    analysis_name: 'release5'
    splicemap:
        working_dir: ../../data/resources/als/DROP/processed_data/aberrant_splicing/datasets/
    outlier:
        splicing:
            working_dir: ../../data/resources/als/DROP/processed_results/aberrant_splicing/datasets/
        expression:
            working_dir: ../../data/resources/als/DROP/processed_results/aberrant_expression/ 
            
proteomics:
    full_results: /s/project/als/analysis/proteomics/results_all.tsv
    full_results_annotated: PROTRIDER_results_annotated.csv
    enrichment: proteomics_enrichment_tissue={tissue}_tissue_pred={tissue_pred}.csv
    true_preds: proteomics_true_preds_tissue={tissue}_tissue_pred={tissue_pred}.csv
        
als_known_genes: als_known_genes/tissue={tissue}_tissue_pred={tissue_pred}_enrichment_known_als_genes.csv
          
          
# Not to change by user
filtering_params:
    vcf:
        format_fields: ['GT','GQ','DP','AD']
        remove_chr: False
        min_GQ: 99
        min_DP_ALT: 10
        filter_long_indels: 10
    count_table:
        update_samples: True
        key_assay: 'RNA_ID'
        value_assay: 'VCF_ID'
        subset_chroms: False
        infer_strand: False
    splicemap:
        use_faster: True
        percentile: 95
        percentile_min_read: 1
        median_cutoff: 1
    outliers:
        padjustGene_cutoff: 0.1
        padjust_junction_cutoff: 0.05
        totalCounts_cutoff: 20
        delta_psi_cutoff: 0.3
        outlier_type: 'psi5__psi3__theta'
        num_junction_outliers_per_samples: 15
    outliers_expression:
        padjust: 0.05
    absplice:
        median_n_cutoff: 10
        tpm_cutoff: 1
        count_cat_cutoff: 20
        
spliceai:
    lookup_only: False
   
method: 'kn'
event_filter: 'median_cutoff'
gtex_version: 'gtex_v8'

use_gene_tpm: False 

# TODO: add motor_neurons
tissue_map_subset: ../../data/resources/gtex_v8/tissue_map_main_tissue.csv

models:
    - spliceai
    # - mmsplice
    - mmsplice_splicemap
    - mmsplice_splicemap_ref_psi
    - spliceai_splicemap
    - spliceai_splicemap_ref_psi
    - absplice_dna

tissues_cat:
    - motor_neuron

# tissue_subsets_for_pred:
tissues_subset:
    - Brain

splicemap_tissues:
    - motor_neuron

tissue_target: motor_neuron

tissues:
    - Brain_Amygdala
    - Brain_Anterior_cingulate_cortex_BA24
    - Brain_Caudate_basal_ganglia
    - Brain_Cerebellar_Hemisphere
    - Brain_Cerebellum
    - Brain_Cortex
    - Brain_Frontal_Cortex_BA9
    - Brain_Hippocampus
    - Brain_Hypothalamus
    - Brain_Nucleus_accumbens_basal_ganglia
    - Brain_Putamen_basal_ganglia
    - Brain_Spinal_cord_cervical_c_1
    - Brain_Substantia_nigra

    - motor_neuron

chroms:
  - 'chr1'
  - 'chr2'
  - 'chr3'
  - 'chr4'
  - 'chr5'
  - 'chr6'
  - 'chr7'
  - 'chr8'
  - 'chr9'
  - 'chr10'
  - 'chr11'
  - 'chr12'
  - 'chr13'
  - 'chr14'
  - 'chr15'
  - 'chr16'
  - 'chr17'
  - 'chr18'
  - 'chr19'
  - 'chr20'
  - 'chr21'  
  - 'chr22'
#   - 'chrX'