gene_id_to_name_mapping_raw: ../../data/resources/common/hugo_symbol_to_ENSG_mapping.tsv  

gnomad:
  maf_db: ../../data/resources/common/{genome}/gnomAD_maf_db/rocksdb/maf.db
  
gene_expression_gtex: 
  raw: ../../data/resources/common/{genome}/gene_expression_tpm/raw_median_tpm.gz
  all_tissues: ../../data/resources/common/{genome}/gene_expression_tpm/all_tissues_tpm.csv
  
spliceai:
  indel_vcf: ../../data/resources/common/{genome}/SpliceAI/spliceai_scores/spliceai_scores.masked.indel.{genome}.vcf.gz
  snv_vcf: ../../data/resources/common/{genome}/SpliceAI/spliceai_scores/spliceai_scores.masked.snv.{genome}.vcf.gz
  db: ../../data/resources/common/{genome}/SpliceAI/spliceai.db

gene_tpm_gtex: ../../data/results/{gtex_version}/junction_annotation/gene_tpm.csv

splicemap_gtex:
    psi5: ../../data/results/{gtex_version}/junction_annotation/splicemap/{tissue}_splicemap_psi5.csv.gz
    psi3: ../../data/results/{gtex_version}/junction_annotation/splicemap/{tissue}_splicemap_psi3.csv.gz
        
absplice:   
  dna: /s/project/absplice/data/results/gtex_v8_with_general_workflow/splicing_predictions/raw_pred/absplice/absplice_training/whole_GTEx/event_filter=median_cutoff/classifier=interpretml/delta_logit_psi__delta_psi__delta_score__splice_site_is_expressed/abs_features=False/AbSplice_DNA_trained_on_whole_GTEx.pkl
  rna: /s/project/absplice/data/results/gtex_v8_with_general_workflow/splicing_predictions/raw_pred/absplice/absplice_training/rna/all_cats/whole_GTEx/event_filter={event_filter}/classifier={classifier}/{feature_string}/abs_features={abs_features}/AbSplice_RNA_trained_on_whole_GTEx.pkl
  # dna: ../../data/results/gtex_v8/splicing_predictions/raw_pred/absplice/absplice_training/whole_GTEx/classifier=interpretml/delta_logit_psi__delta_psi__delta_score__splice_site_is_expressed/abs_features=False/AbSplice_DNA_trained_on_whole_GTEx.pkl
  # rna: ../../data/results/gtex_v8/splicing_predictions/raw_pred/absplice/absplice_training/rna/all_cats/whole_GTEx/classifier=interpretml/delta_logit_psi__delta_psi__delta_score__splice_site_is_expressed/abs_features=False/AbSplice_RNA_trained_on_whole_GTEx.pkl

absplice_matching_cutoffs_in_gtex: ../../data/results/gtex_v8/benchmark/benchmark_results/classifier=interpretml/delta_logit_psi__delta_psi__delta_score__splice_site_is_expressed/abs_features=False/performance/gtex_splicemaps/dna/thresholds/corresponding_thresholds.csv

omim_genes: ../../data/resources/common/omim-genes.tsv
mito_genes: ../../data/resources/common/mito_genes.csv
als_genes: ../../data/resources/common/merged_als_genes.csv
neurological_genes: ../../data/resources/common/fresard_genes.tsv
