# Path to adapt by user
output_dir: 
    junction_annotation: ../../data/results/mito/junction_annotation/
    splicing_preds: ../../data/results/mito/splicing_predictions/
    outliers: ../../data/results/mito/outlier_ground_truth/
    vcf_annotation: ../../data/results/mito/vcf_annotation/
    benchmark: ../../data/results/mito/benchmark/
    reports: ../../data/mito/reports/

genome: 'hg19'
fasta: /s/genomes/Gencode/Gencode_human/release_34/GRCh37_mapping/GRCh37.primary_assembly.genome.fa
gtf: /s/genomes/Gencode/Gencode_human/release_34/GRCh37_mapping/gencode.v34lift37.annotation.gtf.gz

gene_tpm_dataset: ../../data/resources/common/hg19/gene_expression_tpm/Prokisch_Fibroblasts_tpm.csv

vcf: ../../data/resources/mito/vcf_normalized/{vcf_id}.vcf.gz

DROP:
    outlier_ground_truth_all: ../../data/resources/mito/DROP/processed_results/aberrant_splicing/results/v29/fraser/
    tissue_map: ../../data/resources/mito/tissue_map_DROP.csv
    sample_annotation: ../../data/resources/mito/sample_annotation_drop.tsv
    version: 'v29'
    splicemap:
        working_dir: ../../data/resources/mito/DROP/processed_data/aberrant_splicing/datasets/
    outlier:
        splicing:
            working_dir: ../../data/resources/mito/DROP/processed_results/aberrant_splicing/datasets/
        expression:
            working_dir: ../../data/resources/mito/DROP/processed_results/aberrant_expression/
            
# Not to change by user
filtering_params:
    vcf:
        format_fields: ['GT','GQ','DP','AD']
        remove_chr: False
        min_GQ: 99
        min_DP_ALT: 10
        filter_long_indels: 10
    count_table:
        update_samples: True
        key_assay: 'RNA_ID'
        value_assay: 'GENOME_ID'
        subset_chroms: False
        infer_strand: False
    splicemap:
        use_faster: True
        percentile: 95
        percentile_min_read: 1
        median_cutoff: 1
    outliers:
        padjustGene_cutoff: 0.1
        padjust_junction_cutoff: 0.05
        totalCounts_cutoff: 20
        delta_psi_cutoff: 0.3
        outlier_type: 'psi5__psi3__theta'
        num_junction_outliers_per_samples: 15
    absplice:
        median_n_cutoff: 10
        tpm_cutoff: 1
        count_cat_cutoff: 20
        
spliceai:
    lookup_only: False
   
method: 'kn'
event_filter: 'median_cutoff'
gtex_version: 'gtex_v7'

use_gene_tpm: False 

tissue_map_subset: ../../data/resources/gtex_v7/tissue_map_main_tissue.csv

models:
    - spliceai
    # - mmsplice

    # - mtsplice
    # - cadd_splice
    - mmsplice_splicemap
    - mmsplice_splicemap_ref_psi
    - spliceai_splicemap
    - spliceai_splicemap_ref_psi
    - absplice_dna

tissues_cat:
    - Prokisch_Fibroblasts

tissues_subset:
    - Cells_Cultured_fibroblasts

tissue_target: Prokisch_Fibroblasts
tissue_dataset: Prokisch_Fibroblasts

splicemap_tissues:
    - Prokisch_Fibroblasts

tissues:
    - Prokisch_Fibroblasts
    - Cells_Cultured_fibroblasts

    
sampleIDs:
    - 33254G
    - 33281G
    - 35791G
    - 53890G
    - 62524G
    - 62631G
    - 63045G
    - 66744G
    - 68540G
    - 68544G
    - 68546G
    - 68547G
    - 68558G
    - 69340G
    - 71724G
    - 73388G
    - 73804G
    - 93741G
    - 94626G
    - EXT_ITA_PI_SANT01_IDX
    
chroms:
  - 'chr1'
  - 'chr2'
  - 'chr3'
  - 'chr4'
  - 'chr5'
  - 'chr6'
  - 'chr7'
  - 'chr8'
  - 'chr9'
  - 'chr10'
  - 'chr11'
  - 'chr12'
  - 'chr13'
  - 'chr14'
  - 'chr15'
  - 'chr16'
  - 'chr17'
  - 'chr18'
  - 'chr19'
  - 'chr20'
  - 'chr21'  
  - 'chr22'
#   - 'chrX'

    



